name: make-index
on: [push]
jobs:
  make-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: |
          npm install jsdom
          node makeindex.js
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html
          git commit -m "automatic index update"
          git push
