name: index build
on:
  push:
  workflow_dispatch:
jobs:
  make-index:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: |
          cd src
          git clone https://github.com/TST-Project/authority-files.git
          git clone https://github.com/TST-Project/lib.git
          yarn install
          yarn build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: automatic index update
          file_pattern: ./*.html
          commit_user_name: TST Bot
