name: database build
on:
  push:
  workflow_dispatch:
jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous run
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: |
          cd db/_src
          git clone https://github.com/TST-Project/authority-files.git
          yarn install
          #git clone https://github.com/TST-Project/lib.git
          #yarn compilexslt
          echo 'Getting list of changed files'
          git diff --name-only ${{github.head_ref}} $(cat latest_commit) > filelist
          echo 'Updating databases'
          yarn updatedb filelist
          echo 'Writing to latest_commit'
          git rev-parse HEAD > latest_commit

      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: automatic database update
          file_pattern: db/*.db db/_src/latest_commit
          commit_user_name: TST Bot
