name: update-paratexts
on: [push]
jobs:
  update-paratexts:
    runs-on: ubuntu-latest

    steps:
      - name: send dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REP_ACCESS_TOKEN }}
          repository: tst-project/lib
          event-type: trigger-update
